require("plugins.blink-cmp")
require("plugins.figdet")
require("plugins.git-integration")
require("plugins.lsp-conf")
require("plugins.markdown")
require("plugins.mini.hipatterns")
require("plugins.mini.indentscope")
require("plugins.oil")
-- require("plugins.tokyonight")
require("plugins.treesitter")
require("plugins.trouble")
require("plugins.vimtex")
require("plugins.which-key")

-- require("plugins.conform")
-- require("plugins.noice")
-- require("plugins.obsidian-nvim")
-- require("plugins.rust")
-- requirns.plugins.lualine")
