require("vim-modules.lsps.lsp")
require("vim-modules.opts")
require("vim-modules.keymaps")
require("vim-modules.color-overrides")
require("vim-modules.autocmd")
require("vim-modules.colorschemes.isekai-remastered").setup()
require("vim-modules.statusline")
