[general]
font-sans = "JetBrainsMono Nerd Font Mono"
font-mono = "JetBrainsMono Nerd Font Mono"

[bar]
scale = 0.6000000238418579
inset-ends = 0.5
bg = "#222436"
background-opacity = 0
border-color = "#86e1fc"
button-variant = "basic"
button-group-border-color = "#86e1fc"
dropdown-shadow = false
dropdown-freeze-label = false

[[bar.layout]]
monitor = "eDP-1"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "battery",
]
center = ["window-title"]
right = [
    "systray",
    "network",
    "microphone",
    "volume",
    "clock",
]

[styling]
theming-monitor = "eDP-1"
matugen-scheme = "expressive"

[styling.palette]
bg = "#16161e"
surface = "#1e2030"
elevated = "#222436"
fg = "#c8d3f5"
fg-muted = "#828bb8"
primary = "#82aaff"
red = "#ff757f"
yellow = "#ffc777"
green = "#c3e88d"
blue = "#86e1fc"

[modules.battery]
border-color = "status-success"
icon-color = "status-success"
icon-bg-color = "status-success"
label-color = "status-success"

[modules.clock]
format = " %a %b %d %I:%M %p"
icon-show = false
icon-bg-color = "status-info"
label-color = "status-info"

[modules.hyprland-workspaces]
min-workspace-count = 10
monitor-specific = false
show-special = false

[modules.media]
icon-type = "default"
icon-show = false

[modules.microphone]
label-show = false
label-max-length = 25

[modules.notification]
popup-position = "top-center"
popup-max-visible = 4

[modules.volume]
border-color = "status-warning"
icon-color = "status-warning"
icon-bg-color = "status-warning"
label-color = "status-warning"
dropdown-app-icons = "native"

[osd]
enabled = false
border = false

[wallpaper]
engine-enabled = false
