[general]
font-sans = "JetBrainsMono Nerd Font Mono"
font-mono = "JetBrainsMono Nerd Font Mono"

[bar]
scale = 0.75
padding = 0.0
padding-ends = 0.0
location = "bottom"
bg = "#0c0c0c"
border-width = 0
border-color = "#58d1eb"
button-variant = "basic"
button-bg-opacity = 0
button-group-border-color = "#58d1eb"
dropdown-shadow = false
dropdown-freeze-label = false

[[bar.layout]]
monitor = "eDP-1"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "battery",
    "media",
]
center = ["window-title"]
right = [
    "systray",
    "network",
    "microphone",
    "volume",
    "clock",
]

[styling]
rounding = "md"
theming-monitor = "eDP-1"
matugen-scheme = "expressive"

[styling.palette]
bg = "#1a1a1a"
surface = "#0c0c0c"
elevated = "#000000"
fg = "#f6f6ef"
fg-muted = "#c4c5b5"
primary = "#127f98"
red = "#ff5f5f"
yellow = "#e0d561"
green = "#98e024"
blue = "#58d1eb"

[modules.battery]
border-color = "status-success"
icon-color = "status-success"
icon-bg-color = "status-success"
label-color = "status-success"

[modules.clock]
icon-bg-color = "status-info"
label-color = "status-info"
right-click = ""

[modules.hyprland-workspaces]
min-workspace-count = 10
monitor-specific = false
show-special = false

[modules.media]
icon-type = "default"
icon-show = false

[modules.microphone]
label-show = false
label-max-length = 25

[modules.notifications]
popup-position = "top-center"
popup-max-visible = 4

[modules.volume]
border-color = "status-warning"
icon-color = "status-warning"
icon-bg-color = "status-warning"
label-color = "status-warning"
dropdown-app-icons = "native"

[osd]
enabled = false
border = false

[wallpaper]
engine-enabled = false
