# See the full configuration reference: https://rioterm.com/docs/config
force-theme = "dark"
theme = "isekai-remastered"
confirm-before-quit = false

[renderer]
backend = "Webgpu"

[navigation]
mode = "Plain"

[cursor]
shape = 'Block'


[editor]
program = "nvim"
args = []


[fonts]
size = 19
use-drawable-chars = true
disable-warnings-not-found = false

extras = [{ family = "IPAexGothic" }]

symbol-map = [
  { start = "3040", end = "309F", font-family = "IPAexGothic" },
  { start = "30A0", end = "30FF", font-family = "IPAexGothic" },
  { start = "31F0", end = "31FF", font-family = "IPAexGothic" },
  { start = "4E00", end = "9FFF", font-family = "IPAexGothic" },
  { start = "3000", end = "303F", font-family = "IPAexGothic" },
  { start = "FF00", end = "FFEF", font-family = "IPAexGothic" },
]

[fonts.regular]
family = "JetBrainsMono Nerd Font Mono"
style = "default"

[fonts.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "default"

[fonts.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "default"

[fonts.bold-italic]
family = "JetBrainsMono Nerd Font Mono"
style = "default"
