[colors]
background = '#1a1a1a'
black = '#1a1a1a'
blue = '#2ac3e6'
cyan = '#58d1eb'
foreground  = '#f6f6ef'
green = '#98e024'
magenta = '#9d65ff'
red = '#ff5f5f'
white = '#f6f6ef'
yellow = '#fd971f'

# Cursor
cursor = '#fd971f'
vi-cursor = '#58d1eb'

tabs = '#343434'
tabs-active = '#f6f6ef'
split = '#52522e'
split-active = '#58d1eb'

# Search
search-match-background = '#58d1eb'
search-match-foreground = '#f6f6ef'
search-focused-match-background = '#fd971f'
search-focused-match-foreground = '#f6f6ef'

# Selection
selection-foreground = '#f6f6ef'
selection-background = '#343434'

# Dim colors
dim-background = '#1a1a1a'
dim-black = '#1a1a1a'
dim-blue = '#2ac3e6'
dim-cyan = '#58d1eb'
dim-foreground  = '#f6f6ef'
dim-green = '#98e024'
dim-magenta = '#9d65ff'
dim-red = '#ff5f5f'
dim-white = '#f6f6ef'
dim-yellow = '#fd971f'

# Light colors
light-background = '#1a1a1a'
light-black = '#625e4c'
light-blue = '#2ac3e6'
light-cyan = '#58d1eb'
light-foreground  = '#f6f6ef'
light-green = '#98e024'
light-magenta = '#9d65ff'
light-red = '#ff5f5f'
light-white = '#f6f6ef'
light-yellow = '#fd971f'
