virtual_modifiers:
  - FN

keymap:
  - remap:
      KEY_FN-1: F1
      KEY_FN-2: F2
      KEY_FN-3: F3
      KEY_FN-4: F4
      KEY_FN-5: F5
      KEY_FN-6: F6
      KEY_FN-7: F7
      KEY_FN-8: F8
      KEY_FN-9: F9
      KEY_FN-0: F10
      KEY_FN-KEY_MINUS: F11
      KEY_FN-KEY_EQUAL: F12
      Shift-KEY_FN-1: KEY_BRIGHTNESSDOWN
      Shift-KEY_FN-2: KEY_BRIGHTNESSUP
      Shift-KEY_FN-3: KEY_MICMUTE
      Shift-KEY_FN-4: KEY_SEARCH
      Shift-KEY_FN-5: KEY_KBDILLUMDOWN
      Shift-KEY_FN-6: KEY_KBDILLUMUP
      Shift-KEY_FN-7: KEY_PREVIOUSSONG
      Shift-KEY_FN-8: KEY_PLAYPAUSE
      Shift-KEY_FN-9: KEY_NEXTSONG
      Shift-KEY_FN-0: KEY_MUTE
      Shift-KEY_FN-KEY_MINUS: KEY_VOLUMEDOWN
      Shift-KEY_FN-KEY_EQUAL: KEY_VOLUMEUP
