local colors = require("vim-modules.colorschemes.isekai-remastered.colors")
local M = {
  Comment = { fg = colors.comment, italic = true },
  Constant = { fg = colors.orange },
  String = { fg = colors.green },
  Identifier = { fg = colors.cyan },
  Function = { fg = colors.cyan },
  Statement = { fg = colors.red },
  Type = { fg = colors.cyan, bold = true },
  Special = {},
  Keyword = { fg = colors.red },
  Variable = { fg = colors.fg },
  MatchParen = { fg = colors.orange, bold = true },
  Added = { fg = colors.green },
  Changed = { fg = colors.cyan },
  Removed = { fg = colors.crimson },
  ModeMsg = { fg = colors.green },
  ["@module"] = { fg = colors.cyan, bold = true },
  ["@module.builtin"] = { fg = colors.red, bold = true, italic = true },
  ["@keyword"] = { fg = colors.pink, italic = true },
  ["@keyword.conditional"] = { link = "@keyword" },
  ["@keyword.coroutine"] = { fg = colors.teal, italic = true },
  ["@keyword.function"] = { fg = colors.red, bold = true },
  ["@keyword.import"] = { fg = colors.teal },
  ["@keyword.operator"] = { fg = colors.cyan },
  ["@keyword.return"] = { fg = colors.pink, italic = true, bold = true },
  -- ["@keyword.debug"]                = "Debug",
  -- ["@keyword.directive"]            = "PreProc",
  -- ["@keyword.directive.define"]     = "Define",
  -- ["@keyword.exception"]            = "Exception",
  -- ["@keyword.repeat"]               = "Repeat",
  -- ["@keyword.storage"]              = "StorageClass",
  ["@function"] = { fg = colors.blue },
  ["@function.builtin"] = { fg = colors.cyan, bold = true },
  ["@function.call"] = { fg = colors.cyan },
  ["@function.macro"] = { fg = colors.orange },
  ["@function.method"] = { fg = colors.cyan, bold = true },
  ["@function.method.call"] = { fg = colors.cyan, bold = true },
  ["@variable"] = { fg = colors.fg, italic = true },
  ["@variable.builtin"] = { fg = colors.red, italic = true, bold = true },
  ["@variable.member"] = { fg = colors.cyan },
  ["@variable.parameter"] = { fg = colors.yellow1 },
  ["@variable.parameter.builtin"] = { fg = colors.fg, italic = true },
  ["@property"] = { fg = colors.cyan, italic = true },
  ["@constant"] = { fg = colors.orange, nocombine = true, bold = true },
  ["@constant.builtin"] = { fg = colors.pink, bold = true, italic = true },
  ["@constant.macro"] = { fg = colors.cyan, italic = true },
  ["@type"] = { fg = colors.blue, bold = true },
  ["@type.builtin"] = { fg = colors.cyan, bold = true },
  ["@type.definition"] = { fg = colors.fg, bold = true },
  ["@type.qualifier"] = { fg = colors.crimson, bold = true },
  ["@boolean"] = { fg = colors.purple },
  ["@punctuation.delimiter"] = { fg = colors.cyan },
  ["@punctuation.bracket"] = { fg = colors.bracket },
  ["@punctuation.special"] = { fg = colors.cyan, bold = true },
  ["@punctuation.special.markdown"] = { fg = colors.cyan },
  ["@string"] = { fg = colors.green },
  ["@string.documentation"] = { fg = colors.yellow1 },
  ["@string.escape"] = { fg = colors.purple },
  ["@string.regexp"] = { fg = colors.cyan },
  ["@punctuation.delimiter.nu"] = { fg = colors.cyan, bold = true },
  ["@operator"] = { fg = colors.cyan },
  ["@operator.nu"] = { fg = colors.cyan, bold = true },
  ["@markup"] = {},
  ["@markup.emphasis"] = { italic = true },
  ["@markup.environment"] = { fg = colors.orange },
  ["@markup.environment.name"] = { fg = colors.cyan, bold = true },
  ["@markup.heading"] = {},
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = colors.teal },
  ["@markup.link.url"] = { underline = true },
  ["@markup.list"] = { fg = colors.cyan },
  ["@markup.list.checked"] = { fg = colors.green },
  ["@markup.list.markdown"] = { fg = colors.orange, bold = true },
  ["@markup.list.unchecked"] = { fg = colors.cyan },
  ["@markup.math"] = { fg = colors.yellow1 },
  ["@markup.raw"] = { fg = colors.green },
  ["@markup.raw.markdown_inline"] = { bg = colors.black, fg = colors.cyan },
  ["@markup.strikethrough"] = { strikethrough = true },
  ["@markup.strong"] = { bold = true },
  ["@markup.underline"] = { underline = true },
  ["@markup.heading.1"] = { bg = colors.bg, fg = colors.purple, bold = true },
  ["@markup.heading.2"] = { bg = colors.bg, fg = colors.cyan, bold = true },
  ["@markup.heading.3"] = { bg = colors.bg, fg = colors.yellow1, bold = true },
  ["@markup.heading.4"] = { bg = colors.bg, fg = colors.teal, bold = true },
  ["@markup.heading.5"] = { bg = colors.bg, fg = colors.orange, bold = true },
  ["@markup.heading.6"] = { bg = colors.bg, fg = colors.red, bold = true },
  -- ["@markup.link.label"]          = "SpecialChar",
  -- ["@markup.link.label.symbol"]   = "Identifier",
  ["@attribute"] = { fg = colors.cyan, bold = true, italic = true },
  ["@lsp.type.decorator"] = { fg = colors.cyan, bold = true },
  ["@lsp.type.deriveHelper"] = { fg = colors.cyan, bold = true },
  ["@tag.attribute"] = { fg = colors.cyan, italic = true },
  ["@lsp.type.formatSpecifier.rust"] = { fg = colors.cyan },
  ["@lsp.type.class.lua"] = {},
  ["@lsp.type.variable"] = {},
  ["@lsp.mod.declaration"] = {},
  ["@lsp.typemod.variable.declaration"] = {},
  ["@lsp"] = {},
  ["@tag.kdl"] = { fg = colors.cyan },
  ["@property.kdl"] = { fg = colors.pink }
}

return M
