require("modules.autostart")
require("modules.binds")
-- require("modules.colorscheme")
-- require("modules.environment-variables")
require("modules.input")
require("modules.look-and-feel")
require("modules.misc")
require("modules.monitors")
-- require("modules.programs")
require("modules.window-rule-and-workspace-rule")
