[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "black", italic = true }

# Hovered
hovered         = { bg = "black" }
preview_hovered = { bg = "black" }

# Find
find_keyword  = { fg = "#1a1a1a", bg = "cyan", bold = true }
find_position = { fg = "blue", bg = "black", bold = true }

# Marker
marker_copied   = { fg = "green", bg = "green" }
marker_cut      = { fg = "red", bg = "red" }
marker_marked   = { fg = "blue", bg = "blue" }
marker_selected = { fg = "blue", bg = "blue" }

# Count
count_copied   = { fg = "#1a1a1a", bg = "green" }
count_cut      = { fg = "#1a1a1a", bg = "red" }
count_selected = { fg = "#1a1a1a", bg = "blue" }

# Border
border_symbol = "│"
border_style  = { fg = "cyan" }

# Tab
[tabs]
active   = { fg = "black", bg = "blue" }
inactive = { fg = "blue", bg = "#1a1a1a" }

[mode]
normal_main = { fg = "black", bg = "blue", bold = true }
normal_alt  = { fg = "blue", bg = "#1a1a1a" }

select_main = { fg = "black", bg = "blue", bold = true }
select_alt  = { fg = "blue", bg = "#1a1a1a" }

unset_main  = { fg = "black", bg = "red", bold = true }
unset_alt   = { fg = "red", bg = "#1a1a1a" }

[status]
overall   = { fg = 'white', bg = 'black' }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }
# sep_left  = { open = "", close = "" }
# sep_right = { open = "", close = "" }
#
# Progress
progress_label  = { fg = 'white', bold = true }
progress_normal = { fg = 'blue', bg = "#1a1a1a" }
progress_error  = { fg = 'red', bg = "#1a1a1a" }
#
# Permissions
perm_type  = { fg = 'blue' }
perm_read  = { fg = 'yellow' }
perm_write = { fg = 'red' }
perm_exec  = { fg = 'green' }
perm_sep   = { fg = '#1a1a1a' }
#
# [pick]
# border   = { fg = "cyan" }
# active   = { fg = "#c8d3f5",  bg = "#2d3f76" }
# inactive = { fg = "#c8d3f5" }
#
# # Input
# [input]
# border   = { fg = "blue" }
# title    = { fg = "blue" }
# value    = { fg = "pink" }
# selected = { bg = "#2d3f76" }
#
# # Completion
# [cmp]
# border   = { fg = "blue" }
# active   = { fg = "#c8d3f5", bg = "#363c58" }
# inactive = { fg = "#c8d3f5" }
#
# icon_file    = ""
# icon_folder  = ""
# icon_command = ""
#
# # Tasks
# [tasks]
# border  = { fg = "cyan" }
# title   = { fg = "cyan" }
# hovered = { fg = "#c8d3f5", bg = "#2d3f76" }
#
# # Which
# [which]
# cols            = 3
# mask            = { bg = "#1a1a1a" }
# cand            = { fg = "#86e1fc" }
# rest            = { fg = "blue" }
# desc            = { fg = "blue" }
# separator       = " ➜ "
# separator_style = { fg = "#636da6" }
#
# # Confirm
# [confirm]
# border  = { fg = "blue" }
# title   = { fg = "cyan" }
# content = {}
# list    = {}
# btn_yes = { bg = "#2d3f76" }
# btn_no  = {}
# btn_labels = [ "  [Y]es  ", "  (N)o  " ]
#
# # Spot
# [spot]
# border  = { fg = "cyan" }
# title   = { fg = "cyan" }
#
# # Notify
# [notify]
# title_info  = { fg = "blue" }
# title_warn  = { fg = "#ffc777" }
# title_error = { fg = "#c53b53" }
#
# icon_error = ""
# icon_warn = ""
# icon_info = ""
#
# # Help
# [help]
# on      = { fg = "green" }
# run     = { fg = "blue" }
# desc    = { fg = "#86e1fc" }
# hovered = { bg = "#2f334d" }
# footer  = { fg = "#c8d3f5", bg = "#222436" }
#
# # [filetype]
# #
# # rules = [
# # 	# Images
# # 	{ mime = "image/*", fg = "#ffc777" },
# #
# # 	# Media
# # 	{ mime = "{audio,video}/*", fg = "blue" },
# #
# # 	# Archives
# # 	{ mime = "application/*zip", fg = "red" },
# # 	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "red" },
# #
# # 	# Documents
# # 	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#86e1fc" },
# #
# # 	# Empty files
# # 	# { mime = "inode/x-empty", fg = "red" },
# #
# # 	# Special files
# # 	{ name = "*", is = "orphan", bg = "red" },
# # 	{ name = "*", is = "exec"  , fg = "green" },
# #
# # 	# Fallback
# # 	{ name = "*/", fg = "blue" },
# # 	{ name = "*", fg = "#c8d3f5" }
# # ]
# #
