music_directory     "~/Music"
playlist_directory  "~/Music/Playlist/"
db_file             "~/.local/share/mpd/mpd.db"
log_file            "~/.local/share/mpd/mpd.log"
pid_file            "~/.local/share/mpd/mpd.pid"
state_file          "~/.local/share/mpd/mpdstate"
restore_paused      "yes"
auto_update         "yes"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

bind_to_address     "localhost"
port                "6600"

audio_output {
    type            "pipewire"
    name            "CoreAudio"
    device           "defualt"
    format          "44100:16:2"
}

audio_output {
    type        "httpd"
    name        "HTTP Stream"
    encoder     "vorbis"
    port        "8000"
    bind_to_address "localhost"
    quality     "5.0"
    format      "44100:16:2"
}
